name: Jekyll Themes
url: http://gorislab.com
description: Website for the Goris lab at UT Austin

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: rouge
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
